name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this if you want to trigger on a different branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/saladify/serverlesssalad/node-javascript-mysql-demo:latest .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/saladify/serverlesssalad/node-javascript-mysql-demo:latest